version: '3.4'
services:
  freescout-app:
    ports:
      - 88:80
    volumes:
      - freescout-data:/data
      - freescout-logs:/www/logs
    restart: unless-stopped
  freescout-db:
    ports:
      - 3300:3306
    volumes:
      - freescout-db:/var/lib/mysql
    restart: unless-stopped
  freescout-db-backup:
    volumes:
      - freescout-db-backup:/backup
    restart: unless-stopped

volumes:
  freescout-app:
    external:
      name: freescout-data
  freescout-logs:
    external:
      name: freescout-logs
  freescout-db:
    external:
      name: freescout-db
  freescout-db-backup:
    external:
      name: freescout-db-backup

networks:
  bridge:
    external:
      name: bridge
